# Generated by Django 5.2.4 on 2025-07-06 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BogieChecksheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formNumber', models.CharField(max_length=50)),
                ('inspectionBy', models.CharField(max_length=50)),
                ('inspectionDate', models.DateField()),
                ('bogieDetails', models.JSONField()),
                ('bogieChecksheet', models.JSONField()),
                ('bmbcChecksheet', models.JSONField()),
            ],
        ),
        migrations.RenameField(
            model_name='wheelspecification',
            old_name='form_number',
            new_name='formNumber',
        ),
        migrations.RenameField(
            model_name='wheelspecification',
            old_name='submitted_by',
            new_name='submittedBy',
        ),
        migrations.RenameField(
            model_name='wheelspecification',
            old_name='submitted_date',
            new_name='submittedDate',
        ),
    ]
